plugins {
    alias libs.plugins.android.app
    alias libs.plugins.kotlin.android
}

android {
    compileSdk 34
    namespace "org.secuso.privacyfriendlymemory"
    defaultConfig {
        applicationId "org.secuso.privacyfriendlymemory"

        minSdkVersion 17
        targetSdkVersion 34
        versionCode 100
        versionName "1.1.3"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.toString()
    }

    lint {
        lintConfig = file("lint.xml")
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    coreLibraryDesugaring libs.desugar.jdk
    implementation libs.multidex
    testImplementation libs.junit
    implementation libs.ax.appcompat
    implementation libs.material

    // pfa-core library
    implementation project(path: ':model')
    implementation project(path: ':ui-view')

    // Backup
    implementation project(path: ':backup-api')
    implementation libs.ax.work.runtime
    implementation libs.ax.work.runtime.ktx
    androidTestImplementation libs.ax.work.testing
    implementation libs.ax.sqlite.ktx

    constraints {
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.0") {
            because("kotlin-stdlib-jdk7 is now a part of kotlin-stdlib")
        }
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0") {
            because("kotlin-stdlib-jdk8 is now a part of kotlin-stdlib")
        }
    }
}
